py_library(
        name="py_protocol_utils",
        visibility = ["//visibility:public"],
        srcs = glob(["*.py"]),
        deps=[
            "//protocol/src/proto:py_oef_protocol"
        ],
)