py_library(
        name="py_oef",
        visibility = ["//visibility:public"],
        srcs = glob(["*.py"]),
        deps=[
            "//protocol/src/proto:py_oef_protocol",
            "//protocol/src/python:py_protocol_utils",
            "//utils/src/python:py_utils"
        ],
)